# Uncomment the next line to define a global platform for your project

platform :ios, '10.0'

target 'LXSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LXSwift

pod 'Moya', '~> 14.0'
pod 'SnapKit', '~> 5.0.0'
pod 'SVProgressHUD'


end
